// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: internal/proto/attack.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	AuthToken     string                 `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	CpuCores      int32                  `protobuf:"varint,3,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryMb      int64                  `protobuf:"varint,4,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	BandwidthMbps int32                  `protobuf:"varint,5,opt,name=bandwidth_mbps,json=bandwidthMbps,proto3" json:"bandwidth_mbps,omitempty"`
	Location      string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	IsWindows     bool                   `protobuf:"varint,8,opt,name=is_windows,json=isWindows,proto3" json:"is_windows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_internal_proto_attack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_attack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_attack_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *RegisterRequest) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *RegisterRequest) GetMemoryMb() int64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *RegisterRequest) GetBandwidthMbps() int32 {
	if x != nil {
		return x.BandwidthMbps
	}
	return 0
}

func (x *RegisterRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *RegisterRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RegisterRequest) GetIsWindows() bool {
	if x != nil {
		return x.IsWindows
	}
	return false
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AssignedId    string                 `protobuf:"bytes,3,opt,name=assigned_id,json=assignedId,proto3" json:"assigned_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_internal_proto_attack_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_attack_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_attack_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetAssignedId() string {
	if x != nil {
		return x.AssignedId
	}
	return ""
}

type DeregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	AuthToken     string                 `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_internal_proto_attack_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_attack_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_attack_proto_rawDescGZIP(), []int{2}
}

func (x *DeregisterRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *DeregisterRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type DeregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterResponse) Reset() {
	*x = DeregisterResponse{}
	mi := &file_internal_proto_attack_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterResponse) ProtoMessage() {}

func (x *DeregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_attack_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterResponse.ProtoReflect.Descriptor instead.
func (*DeregisterResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_attack_proto_rawDescGZIP(), []int{3}
}

func (x *DeregisterResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	AuthToken     string                 `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,3,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryUsedMb  int64                  `protobuf:"varint,4,opt,name=memory_used_mb,json=memoryUsedMb,proto3" json:"memory_used_mb,omitempty"`
	NetworkMbps   int32                  `protobuf:"varint,5,opt,name=network_mbps,json=networkMbps,proto3" json:"network_mbps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_internal_proto_attack_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_attack_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_attack_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *HeartbeatRequest) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *HeartbeatRequest) GetMemoryUsedMb() int64 {
	if x != nil {
		return x.MemoryUsedMb
	}
	return 0
}

func (x *HeartbeatRequest) GetNetworkMbps() int32 {
	if x != nil {
		return x.NetworkMbps
	}
	return 0
}

type HeartbeatResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Ok           bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	PendingTask  *AttackTask            `protobuf:"bytes,2,opt,name=pending_task,json=pendingTask,proto3" json:"pending_task,omitempty"`
	CancelTaskId string                 `protobuf:"bytes,3,opt,name=cancel_task_id,json=cancelTaskId,proto3" json:"cancel_task_id,omitempty"`
	Kick         bool                   `protobuf:"varint,4,opt,name=kick,proto3" json:"kick,omitempty"`
	// 环境迁移：非空时 worker 须切换到该 controller 地址并重新注册。
	// 旧 controller 进入迁移模式后每条心跳都携带，worker 幂等处理
	// （配置相同则忽略）。
	ReconfigureController string `protobuf:"bytes,5,opt,name=reconfigure_controller,json=reconfigureController,proto3" json:"reconfigure_controller,omitempty"`
	ReconfigureToken      string `protobuf:"bytes,6,opt,name=reconfigure_token,json=reconfigureToken,proto3" json:"reconfigure_token,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_internal_proto_attack_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_attack_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_attack_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HeartbeatResponse) GetPendingTask() *AttackTask {
	if x != nil {
		return x.PendingTask
	}
	return nil
}

func (x *HeartbeatResponse) GetCancelTaskId() string {
	if x != nil {
		return x.CancelTaskId
	}
	return ""
}

func (x *HeartbeatResponse) GetKick() bool {
	if x != nil {
		return x.Kick
	}
	return false
}

func (x *HeartbeatResponse) GetReconfigureController() string {
	if x != nil {
		return x.ReconfigureController
	}
	return ""
}

func (x *HeartbeatResponse) GetReconfigureToken() string {
	if x != nil {
		return x.ReconfigureToken
	}
	return ""
}

type AttackTask struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Target          string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Method          string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Duration        int32                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Threads         int32                  `protobuf:"varint,5,opt,name=threads,proto3" json:"threads,omitempty"`
	PacketSize      int32                  `protobuf:"varint,6,opt,name=packet_size,json=packetSize,proto3" json:"packet_size,omitempty"`
	Mix             bool                   `protobuf:"varint,7,opt,name=mix,proto3" json:"mix,omitempty"`
	Game            string                 `protobuf:"bytes,8,opt,name=game,proto3" json:"game,omitempty"`
	RateLimitPps    int64                  `protobuf:"varint,9,opt,name=rate_limit_pps,json=rateLimitPps,proto3" json:"rate_limit_pps,omitempty"`
	RateLimitBps    int64                  `protobuf:"varint,10,opt,name=rate_limit_bps,json=rateLimitBps,proto3" json:"rate_limit_bps,omitempty"`
	BurstMode       bool                   `protobuf:"varint,12,opt,name=burst_mode,json=burstMode,proto3" json:"burst_mode,omitempty"`
	JitterMs        int32                  `protobuf:"varint,13,opt,name=jitter_ms,json=jitterMs,proto3" json:"jitter_ms,omitempty"`
	SubAttacks      []*SubAttack           `protobuf:"bytes,14,rep,name=sub_attacks,json=subAttacks,proto3" json:"sub_attacks,omitempty"`
	SpoofIp         bool                   `protobuf:"varint,15,opt,name=spoof_ip,json=spoofIp,proto3" json:"spoof_ip,omitempty"`
	FallbackToUdp   bool                   `protobuf:"varint,16,opt,name=fallback_to_udp,json=fallbackToUdp,proto3" json:"fallback_to_udp,omitempty"`
	SelectedWorkers []string               `protobuf:"bytes,17,rep,name=selected_workers,json=selectedWorkers,proto3" json:"selected_workers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AttackTask) Reset() {
	*x = AttackTask{}
	mi := &file_internal_proto_attack_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackTask) ProtoMessage() {}

func (x *AttackTask) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_attack_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackTask.ProtoReflect.Descriptor instead.
func (*AttackTask) Descriptor() ([]byte, []int) {
	return file_internal_proto_attack_proto_rawDescGZIP(), []int{6}
}

func (x *AttackTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AttackTask) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *AttackTask) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AttackTask) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *AttackTask) GetThreads() int32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *AttackTask) GetPacketSize() int32 {
	if x != nil {
		return x.PacketSize
	}
	return 0
}

func (x *AttackTask) GetMix() bool {
	if x != nil {
		return x.Mix
	}
	return false
}

func (x *AttackTask) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *AttackTask) GetRateLimitPps() int64 {
	if x != nil {
		return x.RateLimitPps
	}
	return 0
}

func (x *AttackTask) GetRateLimitBps() int64 {
	if x != nil {
		return x.RateLimitBps
	}
	return 0
}

func (x *AttackTask) GetBurstMode() bool {
	if x != nil {
		return x.BurstMode
	}
	return false
}

func (x *AttackTask) GetJitterMs() int32 {
	if x != nil {
		return x.JitterMs
	}
	return 0
}

func (x *AttackTask) GetSubAttacks() []*SubAttack {
	if x != nil {
		return x.SubAttacks
	}
	return nil
}

func (x *AttackTask) GetSpoofIp() bool {
	if x != nil {
		return x.SpoofIp
	}
	return false
}

func (x *AttackTask) GetFallbackToUdp() bool {
	if x != nil {
		return x.FallbackToUdp
	}
	return false
}

func (x *AttackTask) GetSelectedWorkers() []string {
	if x != nil {
		return x.SelectedWorkers
	}
	return nil
}

type SubAttack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Threads       int32                  `protobuf:"varint,2,opt,name=threads,proto3" json:"threads,omitempty"`
	PacketSize    int32                  `protobuf:"varint,3,opt,name=packet_size,json=packetSize,proto3" json:"packet_size,omitempty"`
	RateLimitPps  int64                  `protobuf:"varint,4,opt,name=rate_limit_pps,json=rateLimitPps,proto3" json:"rate_limit_pps,omitempty"`
	RateLimitBps  int64                  `protobuf:"varint,5,opt,name=rate_limit_bps,json=rateLimitBps,proto3" json:"rate_limit_bps,omitempty"`
	Game          string                 `protobuf:"bytes,6,opt,name=game,proto3" json:"game,omitempty"`
	BurstMode     bool                   `protobuf:"varint,7,opt,name=burst_mode,json=burstMode,proto3" json:"burst_mode,omitempty"`
	JitterMs      int32                  `protobuf:"varint,8,opt,name=jitter_ms,json=jitterMs,proto3" json:"jitter_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubAttack) Reset() {
	*x = SubAttack{}
	mi := &file_internal_proto_attack_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubAttack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubAttack) ProtoMessage() {}

func (x *SubAttack) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_attack_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubAttack.ProtoReflect.Descriptor instead.
func (*SubAttack) Descriptor() ([]byte, []int) {
	return file_internal_proto_attack_proto_rawDescGZIP(), []int{7}
}

func (x *SubAttack) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *SubAttack) GetThreads() int32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *SubAttack) GetPacketSize() int32 {
	if x != nil {
		return x.PacketSize
	}
	return 0
}

func (x *SubAttack) GetRateLimitPps() int64 {
	if x != nil {
		return x.RateLimitPps
	}
	return 0
}

func (x *SubAttack) GetRateLimitBps() int64 {
	if x != nil {
		return x.RateLimitBps
	}
	return 0
}

func (x *SubAttack) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

func (x *SubAttack) GetBurstMode() bool {
	if x != nil {
		return x.BurstMode
	}
	return false
}

func (x *SubAttack) GetJitterMs() int32 {
	if x != nil {
		return x.JitterMs
	}
	return 0
}

type WorkerStatsPush struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId       string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	PacketsSent    uint64                 `protobuf:"varint,3,opt,name=packets_sent,json=packetsSent,proto3" json:"packets_sent,omitempty"`
	BytesSent      uint64                 `protobuf:"varint,4,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	Errors         uint64                 `protobuf:"varint,5,opt,name=errors,proto3" json:"errors,omitempty"`
	CurrentPps     uint64                 `protobuf:"varint,6,opt,name=current_pps,json=currentPps,proto3" json:"current_pps,omitempty"`
	CurrentBps     uint64                 `protobuf:"varint,7,opt,name=current_bps,json=currentBps,proto3" json:"current_bps,omitempty"`
	ElapsedSeconds float64                `protobuf:"fixed64,8,opt,name=elapsed_seconds,json=elapsedSeconds,proto3" json:"elapsed_seconds,omitempty"`
	Finished       bool                   `protobuf:"varint,9,opt,name=finished,proto3" json:"finished,omitempty"`
	ErrorMsg       string                 `protobuf:"bytes,10,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkerStatsPush) Reset() {
	*x = WorkerStatsPush{}
	mi := &file_internal_proto_attack_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerStatsPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStatsPush) ProtoMessage() {}

func (x *WorkerStatsPush) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_attack_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStatsPush.ProtoReflect.Descriptor instead.
func (*WorkerStatsPush) Descriptor() ([]byte, []int) {
	return file_internal_proto_attack_proto_rawDescGZIP(), []int{8}
}

func (x *WorkerStatsPush) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *WorkerStatsPush) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerStatsPush) GetPacketsSent() uint64 {
	if x != nil {
		return x.PacketsSent
	}
	return 0
}

func (x *WorkerStatsPush) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *WorkerStatsPush) GetErrors() uint64 {
	if x != nil {
		return x.Errors
	}
	return 0
}

func (x *WorkerStatsPush) GetCurrentPps() uint64 {
	if x != nil {
		return x.CurrentPps
	}
	return 0
}

func (x *WorkerStatsPush) GetCurrentBps() uint64 {
	if x != nil {
		return x.CurrentBps
	}
	return 0
}

func (x *WorkerStatsPush) GetElapsedSeconds() float64 {
	if x != nil {
		return x.ElapsedSeconds
	}
	return 0
}

func (x *WorkerStatsPush) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *WorkerStatsPush) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type StatsAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsAck) Reset() {
	*x = StatsAck{}
	mi := &file_internal_proto_attack_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsAck) ProtoMessage() {}

func (x *StatsAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_attack_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsAck.ProtoReflect.Descriptor instead.
func (*StatsAck) Descriptor() ([]byte, []int) {
	return file_internal_proto_attack_proto_rawDescGZIP(), []int{9}
}

func (x *StatsAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_internal_proto_attack_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_attack_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_attack_proto_rawDescGZIP(), []int{10}
}

func (x *ScanRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ScanRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type ScanResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	ResponseSize  int32                  `protobuf:"varint,3,opt,name=response_size,json=responseSize,proto3" json:"response_size,omitempty"`
	ServerName    string                 `protobuf:"bytes,4,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	IsReflector   bool                   `protobuf:"varint,5,opt,name=is_reflector,json=isReflector,proto3" json:"is_reflector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResult) Reset() {
	*x = ScanResult{}
	mi := &file_internal_proto_attack_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResult) ProtoMessage() {}

func (x *ScanResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_attack_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResult.ProtoReflect.Descriptor instead.
func (*ScanResult) Descriptor() ([]byte, []int) {
	return file_internal_proto_attack_proto_rawDescGZIP(), []int{11}
}

func (x *ScanResult) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ScanResult) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ScanResult) GetResponseSize() int32 {
	if x != nil {
		return x.ResponseSize
	}
	return 0
}

func (x *ScanResult) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ScanResult) GetIsReflector() bool {
	if x != nil {
		return x.IsReflector
	}
	return false
}

var File_internal_proto_attack_proto protoreflect.FileDescriptor

const file_internal_proto_attack_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/proto/attack.proto\x12\anettool\"\xfd\x01\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\tR\tauthToken\x12\x1b\n" +
	"\tcpu_cores\x18\x03 \x01(\x05R\bcpuCores\x12\x1b\n" +
	"\tmemory_mb\x18\x04 \x01(\x03R\bmemoryMb\x12%\n" +
	"\x0ebandwidth_mbps\x18\x05 \x01(\x05R\rbandwidthMbps\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"is_windows\x18\b \x01(\bR\tisWindows\"g\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vassigned_id\x18\x03 \x01(\tR\n" +
	"assignedId\"O\n" +
	"\x11DeregisterRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\tR\tauthToken\"$\n" +
	"\x12DeregisterResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xb8\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\tR\tauthToken\x12\x1f\n" +
	"\vcpu_percent\x18\x03 \x01(\x01R\n" +
	"cpuPercent\x12$\n" +
	"\x0ememory_used_mb\x18\x04 \x01(\x03R\fmemoryUsedMb\x12!\n" +
	"\fnetwork_mbps\x18\x05 \x01(\x05R\vnetworkMbps\"\xf9\x01\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x126\n" +
	"\fpending_task\x18\x02 \x01(\v2\x13.nettool.AttackTaskR\vpendingTask\x12$\n" +
	"\x0ecancel_task_id\x18\x03 \x01(\tR\fcancelTaskId\x12\x12\n" +
	"\x04kick\x18\x04 \x01(\bR\x04kick\x125\n" +
	"\x16reconfigure_controller\x18\x05 \x01(\tR\x15reconfigureController\x12+\n" +
	"\x11reconfigure_token\x18\x06 \x01(\tR\x10reconfigureToken\"\xfd\x03\n" +
	"\n" +
	"AttackTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x05R\bduration\x12\x18\n" +
	"\athreads\x18\x05 \x01(\x05R\athreads\x12\x1f\n" +
	"\vpacket_size\x18\x06 \x01(\x05R\n" +
	"packetSize\x12\x10\n" +
	"\x03mix\x18\a \x01(\bR\x03mix\x12\x12\n" +
	"\x04game\x18\b \x01(\tR\x04game\x12$\n" +
	"\x0erate_limit_pps\x18\t \x01(\x03R\frateLimitPps\x12$\n" +
	"\x0erate_limit_bps\x18\n" +
	" \x01(\x03R\frateLimitBps\x12\x1d\n" +
	"\n" +
	"burst_mode\x18\f \x01(\bR\tburstMode\x12\x1b\n" +
	"\tjitter_ms\x18\r \x01(\x05R\bjitterMs\x123\n" +
	"\vsub_attacks\x18\x0e \x03(\v2\x12.nettool.SubAttackR\n" +
	"subAttacks\x12\x19\n" +
	"\bspoof_ip\x18\x0f \x01(\bR\aspoofIp\x12&\n" +
	"\x0ffallback_to_udp\x18\x10 \x01(\bR\rfallbackToUdp\x12)\n" +
	"\x10selected_workers\x18\x11 \x03(\tR\x0fselectedWorkers\"\xfa\x01\n" +
	"\tSubAttack\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x18\n" +
	"\athreads\x18\x02 \x01(\x05R\athreads\x12\x1f\n" +
	"\vpacket_size\x18\x03 \x01(\x05R\n" +
	"packetSize\x12$\n" +
	"\x0erate_limit_pps\x18\x04 \x01(\x03R\frateLimitPps\x12$\n" +
	"\x0erate_limit_bps\x18\x05 \x01(\x03R\frateLimitBps\x12\x12\n" +
	"\x04game\x18\x06 \x01(\tR\x04game\x12\x1d\n" +
	"\n" +
	"burst_mode\x18\a \x01(\bR\tburstMode\x12\x1b\n" +
	"\tjitter_ms\x18\b \x01(\x05R\bjitterMs\"\xc5\x02\n" +
	"\x0fWorkerStatsPush\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12!\n" +
	"\fpackets_sent\x18\x03 \x01(\x04R\vpacketsSent\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x04 \x01(\x04R\tbytesSent\x12\x16\n" +
	"\x06errors\x18\x05 \x01(\x04R\x06errors\x12\x1f\n" +
	"\vcurrent_pps\x18\x06 \x01(\x04R\n" +
	"currentPps\x12\x1f\n" +
	"\vcurrent_bps\x18\a \x01(\x04R\n" +
	"currentBps\x12'\n" +
	"\x0felapsed_seconds\x18\b \x01(\x01R\x0eelapsedSeconds\x12\x1a\n" +
	"\bfinished\x18\t \x01(\bR\bfinished\x12\x1b\n" +
	"\terror_msg\x18\n" +
	" \x01(\tR\berrorMsg\"\x1a\n" +
	"\bStatsAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"1\n" +
	"\vScanRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"\x99\x01\n" +
	"\n" +
	"ScanResult\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12#\n" +
	"\rresponse_size\x18\x03 \x01(\x05R\fresponseSize\x12\x1f\n" +
	"\vserver_name\x18\x04 \x01(\tR\n" +
	"serverName\x12!\n" +
	"\fis_reflector\x18\x05 \x01(\bR\visReflector2\x97\x02\n" +
	"\vNodeService\x12?\n" +
	"\bRegister\x12\x18.nettool.RegisterRequest\x1a\x19.nettool.RegisterResponse\x12E\n" +
	"\n" +
	"Deregister\x12\x1a.nettool.DeregisterRequest\x1a\x1b.nettool.DeregisterResponse\x12B\n" +
	"\tHeartbeat\x12\x19.nettool.HeartbeatRequest\x1a\x1a.nettool.HeartbeatResponse\x12<\n" +
	"\vReportStats\x12\x18.nettool.WorkerStatsPush\x1a\x11.nettool.StatsAck(\x01B\x18Z\x16newtool/internal/protob\x06proto3"

var (
	file_internal_proto_attack_proto_rawDescOnce sync.Once
	file_internal_proto_attack_proto_rawDescData []byte
)

func file_internal_proto_attack_proto_rawDescGZIP() []byte {
	file_internal_proto_attack_proto_rawDescOnce.Do(func() {
		file_internal_proto_attack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_attack_proto_rawDesc), len(file_internal_proto_attack_proto_rawDesc)))
	})
	return file_internal_proto_attack_proto_rawDescData
}

var file_internal_proto_attack_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_proto_attack_proto_goTypes = []any{
	(*RegisterRequest)(nil),    // 0: nettool.RegisterRequest
	(*RegisterResponse)(nil),   // 1: nettool.RegisterResponse
	(*DeregisterRequest)(nil),  // 2: nettool.DeregisterRequest
	(*DeregisterResponse)(nil), // 3: nettool.DeregisterResponse
	(*HeartbeatRequest)(nil),   // 4: nettool.HeartbeatRequest
	(*HeartbeatResponse)(nil),  // 5: nettool.HeartbeatResponse
	(*AttackTask)(nil),         // 6: nettool.AttackTask
	(*SubAttack)(nil),          // 7: nettool.SubAttack
	(*WorkerStatsPush)(nil),    // 8: nettool.WorkerStatsPush
	(*StatsAck)(nil),           // 9: nettool.StatsAck
	(*ScanRequest)(nil),        // 10: nettool.ScanRequest
	(*ScanResult)(nil),         // 11: nettool.ScanResult
}
var file_internal_proto_attack_proto_depIdxs = []int32{
	6, // 0: nettool.HeartbeatResponse.pending_task:type_name -> nettool.AttackTask
	7, // 1: nettool.AttackTask.sub_attacks:type_name -> nettool.SubAttack
	0, // 2: nettool.NodeService.Register:input_type -> nettool.RegisterRequest
	2, // 3: nettool.NodeService.Deregister:input_type -> nettool.DeregisterRequest
	4, // 4: nettool.NodeService.Heartbeat:input_type -> nettool.HeartbeatRequest
	8, // 5: nettool.NodeService.ReportStats:input_type -> nettool.WorkerStatsPush
	1, // 6: nettool.NodeService.Register:output_type -> nettool.RegisterResponse
	3, // 7: nettool.NodeService.Deregister:output_type -> nettool.DeregisterResponse
	5, // 8: nettool.NodeService.Heartbeat:output_type -> nettool.HeartbeatResponse
	9, // 9: nettool.NodeService.ReportStats:output_type -> nettool.StatsAck
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_proto_attack_proto_init() }
func file_internal_proto_attack_proto_init() {
	if File_internal_proto_attack_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_attack_proto_rawDesc), len(file_internal_proto_attack_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_attack_proto_goTypes,
		DependencyIndexes: file_internal_proto_attack_proto_depIdxs,
		MessageInfos:      file_internal_proto_attack_proto_msgTypes,
	}.Build()
	File_internal_proto_attack_proto = out.File
	file_internal_proto_attack_proto_goTypes = nil
	file_internal_proto_attack_proto_depIdxs = nil
}
